### ISSUE TITLE
lots of strings to say zero

### ISSUE THREAD

**Issue by alexcjohnson** [jonschlinkert/is-number#1]
"0.0"
"0.000"
"0.0e+5"
"000"
All of these return false at present

**Comment by jonschlinkert** [comment]
Are you saying the tests are failing? also are you using io or node? thanks

**Comment by alexcjohnson** [comment]
I haven't looked at the tests, just noticed that these didn't give me the answer I expected. I'm using it in the browser (chrome)

**Comment by jonschlinkert** [comment]
> I'm using it in the browser (chrome)

Okay, good to know. Hmm, I'm guessing these are being evaluated as strings...? are you getting the expected result with just `0` and other numbers? just trying to narrow down what it is

**Comment by alexcjohnson** [comment]
Yes, I'm doing things like `isNumber('0.0')`
FWIW, I discovered this by looking at your logic - the first clause `!!(+n)` gives a false negative for anything that evaluates to zero, then to compensate you whitelist some explicit zero values - but there are a lot more strings that evaluate to zero than just `'0'` - so now the question is, is there an efficient test for such strings, or do we need some other strategy than whitelisting?

Another family of zero strings: `"0x00..."`

**Comment by alexcjohnson** [comment]
And to your other question - every other actual number and nonzero number string I've tried works correctly. It's just strings that cast to zero.

What about explicitly checking if it's a string and `+n === 0` but `n !== ''`? Far as I can tell the empty string is the only one that casts to zero erroneously, is that correct?

**Comment by jonschlinkert** [comment]
> Yes, I'm doing things like isNumber('0.0')

Can you try doing it without the quotes? `isNumber(0.0)`, since `"0.0"` won't be cast to an integer. 

> What about explicitly checking if it's a string

It's a little trickier than that, see [this gist](https://gist.github.com/jonschlinkert/e30c70c713da325d0e81), I link to it on the readme. thanks for the additional detail

**Comment by alexcjohnson** [comment]
> Can you try doing it without the quotes?

Oh absolutely, `isNumber(0.0)` works correctly, as do all of the other examples if they are written as numbers and not strings.

> It's a little trickier than that

Yes, it's always trickier than that in javascript, isn't it :smiling_imp: 

Here is a more complete set of test cases - note that each is part of a larger family with an arbitrary number of leading/trailing zeros and arbitrary exponent. You can see that all the strings which cast to nonzero numbers return `true` while all those that cast to zero return false - but clearly if `'0.1'` is a number, `'0.0'` should be as well.

```javascript
isNumber('0.0') // false
isNumber('0.1') // true

isNumber('0x0') // false
isNumber('0x1') // true

isNumber('0e+5') // false
isNumber('1e+5') // true

isNumber('000') // false
isNumber('001') // true

isNumber('0.0E-5') // false
isNumber('0.1E-5') // true

isNumber('0.0E5') // false
isNumber('0.1E5') // true
```

**Comment by jonschlinkert** [comment]
> works correctly, as do all of the other examples if they are written as numbers and not strings.

lol, well the lib is called "is-number" after all. jk I also created the lib to cover this use case. Let me think about this one, I'm open to ideas. This might sound silly but (to have fun) I was trying to use the least code possible to yield a correct result. forces me to learn :)

**Comment by alexcjohnson** [comment]
OK, it's a little odd, but this seems to pass your tests plus mine:

```javascript
function isNumber(n) {
  return !!(+('1'+n) || +(n+'1')) && !Array.isArray(n) && isFinite(n) && (n !== '');
}
```

`'1'+n` catches all the zero strings except `'0x00...'` and `n+'1'` catches all of them except exponential notation.

Also need to add `''` to `shouldFail`

https://gist.github.com/alexcjohnson/a3b74c73a9d4ef872895

Not sure about performance... it may actually be faster in a lot of cases to put the `+n` back in front of `+('1'+n)`

**Comment by alexcjohnson** [comment]
Interesting, at least on these test cases it *is* faster with the `+n` present - but looks like jQuery 2 still has it beat.

http://jsperf.com/isnumeric-jquery-and-alternate

**Comment by jonschlinkert** [comment]
Nice, I tested and benchmarked the code you linked to, but with node.js, and it looks like the `parseFloat` function is about 4% faster. More importantly, it also passes all tests including the string versions of numbers you were having an issue with. 

You already know all of this though :) do you want to do a pr with this code?

```js
module.exports = function isNumber(n) {
  return !Array.isArray(n) && (n - parseFloat(n) + 1) >= 0;
};
```
Or I can add it and link to this issue. Also, we will need to add a link to jquery's source code with attribution.

thanks!

**Comment by alexcjohnson** [comment]
Ah, good to know how it translates to node - the code we're running with this is executed in both node and browsers.

I'll let you do the honors :)

**Comment by alexcjohnson** [comment]
Here's the jquery source btw:
https://github.com/jquery/jquery/blob/master/src/core.js#L206-L212

Comforting to know that even a library as widely used as jquery missed a case until recently!

**Comment by jonschlinkert** [comment]
> I'll let you do the honors :)

sounds good, I'll mention you in the commit. 

> Comforting to know that even a library as widely used as jquery missed a case until recently!

indeed! 

I can also browserify if you want, or do you prefer doing that on your side?

**Comment by alexcjohnson** [comment]
Browserify is part of our build process, so no need to do that on my account.

**Comment by jonschlinkert** [comment]
all of the given use cases should now be passing. please see https://github.com/jonschlinkert/is-number/commit/6cf6bd2b5193d7b63795264ccdeefdaad42dc38a. This was the fastest implementation I could come up with, it covers every use case that jquery covers, but it's 30% faster.

**Comment by alexcjohnson** [comment]
Oh wow, on my machine it's even better than that in browsers, nearly twice as fast as jQuery2 in Chrome, and almost 3x as fast in Firefox!
http://jsperf.com/isnumeric-jquery-and-alternate/2

However, it thinks the empty string `''` is a number. All the other test cases look good.

**Comment by jonschlinkert** [comment]
> However, it thinks the empty string ''

I fixed that, saw it as well lol. sorry I have another patch, I'll push up in a bit

**Comment by jonschlinkert** [comment]
> Oh wow, on my machine it's even better than that in browsers, nearly twice as fast as jQuery2 in Chrome, and almost 3x as fast in Firefox!

that's great! thanks for benchmarking!

**Comment by alexcjohnson** [comment]
Not sure if this is the patch you had in mind, but just adding `&& n !== ''` at the end slows it a little but leaves it still nearly twice as fast as jquery2. I simplified it a tiny bit, leading to a small additional bump on chrome and safari...
```
function isNumberAJ1(n) {
    return n !== null && !Array.isArray(n)
        && ((+n) - n) < 1 && n !== '';
}
```
Then I tried to reorder the clauses, on the theory that the most complex test should happen first because it's the most likely to fail and short-circuit the others. Somehow that causes performance to tank, which doesn't make much sense to me but there it is.
http://jsperf.com/isnumeric-jquery-and-alternate/3

**Comment by jonschlinkert** [comment]
thanks for looking into it more. unfortunately that fails several of the tests. 
![screen shot 2015-05-03 at 12 20 37 am](https://cloud.githubusercontent.com/assets/383994/7443637/57316eac-f12a-11e4-9bcf-6c954a7f215c.png)

The code I just pushed up passes everything, I added a bunch of new tests, and it's only about 20% slower - so hopefully still faster than other libs (and I think yields better results thanks to you!)

**Comment by alexcjohnson** [comment]
Oh man, I really should be sleeping instead of continuing to fiddle with this, but it's even better if you only make it cast once (`n - n` casts `n` to a number twice).
http://jsperf.com/isnumeric-jquery-and-alternate/4
```javascript
function isNumber(n) {
    if(Array.isArray(n) || n === null || n === '') return false;
    n = +n;
    return n - n < 1;
}
```

**Comment by alexcjohnson** [comment]
oh whoops - didn't see your last note... let me look at it some more :frowning:

**Comment by alexcjohnson** [comment]
Yikes, `true`, `false`, and `Date` - pretty important additions to the test suite! FWIW, jQuery2 still passes this. I've put your new one and jQuery2 in http://jsperf.com/isnumeric-jquery-and-alternate/4 - along with a mod inspired by the fiddling I was just doing, to make sure you only cast once, which still seems to help a bit. Oddly enough Chrome doesn't care the new one (though it's a wash post-tweak), but Firefox and Safari love it!

my tweak:
```
function isNumber(n) {
  var type = typeOf(n);
  if ((type !== 'number' && type !== 'string') || n === '') {
    return false;
  }
  n = +n;
  return (n - n) < 1;
}
```

**Comment by jonschlinkert** [comment]
lol I know what you're saying. I think about this stuff too much. Doing what you suggested made it about 30% faster! thanks!

updated, bumped and published!

**Comment by alexcjohnson** [comment]
Excellent, I think we can finally put this one to bed... for now :smile_cat:

**Comment by jonschlinkert** [comment]
lol :+1:
