### ISSUE TITLE
Better Solution

### ISSUE THREAD

**Issue by Varun-Sethu** [jonschlinkert/is-number#11]
Your solution seems rather complicated... You might want to try this solution:
```js
var x = 3.422222222;
var y = 3;
console.log(/^\d+$/.test(x) || /[+-]?([0-9]*[.])?[0-9]+/.test(x));
// True
console.log(/^\d+$/.test(y) || /[+-]?([0-9]*[.])?[0-9]+/.test(y));
// True
```

**Comment by jonschlinkert** [comment]
Does your solution pass 100% of the unit tests?

**Comment by jonschlinkert** [comment]
closing due to lack of response and since this would clearly fail a number of the unit tests
