### ISSUE TITLE
Why use trim here? 

### ISSUE THREAD

**Issue by buoyantair** [jonschlinkert/is-number#12]
Hi, can someone tell me why the trim function is used against the empty string here?
https://github.com/jonschlinkert/is-number/blob/0c6b15a88bc10cd47f67a09506399dfc9ddc075d/index.js#L15

Because as you can see below (in the terminal), It looks like js is coercing the string to true just by doing `!""`. 
![image](https://user-images.githubusercontent.com/5159834/35484658-e4f25aa8-0478-11e8-9f0d-5f9cc40cc066.png)

**Comment by jonschlinkert** [comment]
Because whitespace evaluates to `true`

**Comment by buoyantair** [comment]
Oh cool, thank you @jonschlinkert !
