### ISSUE TITLE
Should strings with a number and whitespaces pass?

### ISSUE THREAD

**Issue by VladShcherbin** [jonschlinkert/is-number#13]
Hey, should a string with whitespaces be a number:

```js
var isNumber = require('is-number')
console.log(isNumber('   3 ')) // -> true
```

I'd expect it to be false.

**Comment by VladShcherbin** [comment]
Sorry, my bad 🤦‍♂️

**Comment by jonschlinkert** [comment]
@VladShcherbin don't feel bad, this was a perfectly valid question. thanks for the issue
