### ISSUE TITLE
What's the purpose of these test cases?

### ISSUE THREAD

**Issue by CoderLim** [jonschlinkert/is-number#16]
In `test.js`:

 // All these computed to NaN, any different?
 +'abc',
 +/foo/,
 +[1, 2, 4],

// Why triple +function?
+function() {},
+function() {},
+function() {},

what's the purpose above？ thx.

**Comment by jonschlinkert** [comment]
> Why triple +function?

idk, probably just duplicates from how they were generated when I created the tests. this library was created for checking values from parsing a string, some of the tests were just copy/pasted from whatever I was parsing at the time. 

> All these computed to NaN, any different?

No, same reason.
