### ISSUE TITLE
isNumber(new Number(5)) is false

### ISSUE THREAD

**Issue by hackhat** [jonschlinkert/is-number#18]
I'd never use `new Number` but I think is a use case that should be handled... because is actually a number.

**Comment by lessfish** [comment]
it will return `true`, what's your code?

**Comment by lessfish** [comment]
I'm sorry, I see the lib of 4.0.0, so the feature is removed, I don't know why

**Comment by bodadotsh** [comment]
The use of Number constructor `new Number()` is believed to be [a bad practice](https://eslint.org/docs/rules/no-new-wrappers#rule-details) by [many](https://stackoverflow.com/questions/41458001/why-to-avoid-creating-objects-in-javascript) so the lib is right in keeping things consistent

**Comment by jonschlinkert** [comment]
Closing, for the same reasons mentioned by @bodazhao in https://github.com/jonschlinkert/is-number/issues/18#issuecomment-532468827
