### ISSUE TITLE
Bigint support

### ISSUE THREAD

**Issue by tomtheisen** [jonschlinkert/is-number#22]
Bigint is now supported by chrome and node.  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

This library is not compatible with these numbers.  `isNumber(7n)` reports `false`.

**Comment by doowb** [comment]
According to the documentation that you linked, it is not recommended to coerce variables between `Number` and `BigInt`. It also states that native `Math` methods do not work with `BigInt`.

Because of these restrictions, I don't think `is-number` should return `true` for `BigInt`.
