### ISSUE TITLE
Whitespace strings return true

### ISSUE THREAD

**Issue by alexcjohnson** [jonschlinkert/is-number#3]
Unfortunately the empty string is not the only one that casts to zero without containing a number:
```javascript
isNumber('   ') // true
isNumber('\r\n\t') // true
```

I guess there need to be some whitespace strings in the test arrays. Probably also some strings with numbers AND whitespace, which are (correctly) recognized as numbers currently:
```javascript
isNumber('   56\r\n  ') // true
```

FWIW, for my own purposes I decided I was OK abandoning the Number and String objects - `n = new Number(1)` and `n = new String('1')` - and so was able to simplify to:

```javascript
module.exports = function(n) {
    if(n === '') return false;

    var type = typeof n;
    if(type === 'string') n = +n;
    else if(type !== 'number') return false;

    return n - n < 1;
};
```
which runs 2-3x faster than the more general case using `kind-of`. Notice in particular that you only have to cast if you don't already have a number.

And then I could handle the whitespace without too much overhead by:

```javascript
module.exports = function(n) {
    var type = typeof n;
    if(type === 'string') {
        var original = n;
        n = +n;
        // whitespace strings cast to zero - filter them out
        if(n===0 && !original.trim()) return false;
    }
    else if(type !== 'number') return false;

    return n - n < 1;
}
```

**Comment by tunnckoCore** [comment]
ha, good catch!
but it will fail for `1`

**Comment by alexcjohnson** [comment]
@tunnckoCore you mean `isNumber(1)` or `isNumber('1')` ? Both of those work in my tests.

**Comment by jonschlinkert** [comment]
hmm, I think we just need to use parseInt or something a bit more durable. I'll take another look

**Comment by jonschlinkert** [comment]
thanks for reporting
