### ISSUE TITLE
44kb of uncompressed code

### ISSUE THREAD

**Issue by dfcreative** [jonschlinkert/is-number#4]
Hello!
I found this lib in npm, hoping to use it as a simple number checker for [slider component](http://github.com/dfcreative/slidy).
When I came up to standalone build, I found that it compiles to too much of code. Digging into details, I found out that simple `require('is-number')` with nothing else but self, browserified results in 44kb of uncompressed code. That is because `is-number` requires `kind-of`, which requires `Buffer` and other platform stuff.
So I think, is it really reasonable to keep such a stack of code just for simple ponyfill-like number checker? In that case one could require `jQuery` or `underscore`, sorry.
So as a temporary solution I’ve taken [mutype/is-number](https://github.com/dfcreative/mutype/blob/master/is-number.js), or [101/is-number](https://github.com/tjmehta/101/blob/master/is-number.js), but I leave this note here, just in case :)

**Comment by jonschlinkert** [comment]
> with nothing else but self, browserified results in 44kb of uncompressed code.

That's insane. I agree, that needs to be reduced thanks for letting me know. 

> is it really reasonable to keep such a stack of code just for simple ponyfill-like number checker?

Let me try to rephrase:

```js
is it really reasonable to [try to be correct] for simple ponyfill-like number checker?
```

Yes. 

```
is it really [pragmatic] to keep such a stack of code [now that you know the footprint] just for simple ponyfill-like number checker?
```
No.

based on conversations with @alexcjohnson I was planning to make changes to this anyway, I can also make changes to [kind-of](https://github.com/jonschlinkert/kind-of), thanks for bringing this to my attention.

@alexcjohnson any thoughts?

**Comment by alexcjohnson** [comment]
@jonschlinkert just for a bit of background on my own use case, Plotly found that for certain large plots, up to three quarters of the rendering time was spent calling `$.isNumeric` :scream: and we're trying to get rid of jQuery from our main plotting library anyway. So my main criterion was speed, and entirely in a browser context (almost - we call it from node ourselves but in that case we know all the input is coming from json so it's easier).

What we're using now is this one: https://gist.github.com/alexcjohnson/74902c646f08f456dd56 which is quite fast (and pretty small, though that doesn't matter too much to me), and as far as I can tell gets all the answers right EXCEPT that I've explicitly chosen to drop support for number and string constructors (do those have a legitimate use case? Please say no :hear_no_evil: ) If you see anything else I've missed with this I'd love to hear about it!

If one wanted to extend what I started with to support these oddballs, I expect it wouldn't be hard at all (and probably a minimal performance hit) to wedge something in right before `else if(type !== 'number')`, something like:
```
else if(type === 'object') {
    if(n instanceof String) {
        /* do the original string block */
    }
    else if(!(n instanceof Number)) return false;
}
```

**Comment by vcekov** [comment]
Isn't this whole isNumber just ``typeof value === "number" && isFinite(value);`` ?

**Comment by alexcjohnson** [comment]
@vcekov the goal is to support numeric strings as well - check out the [tests](https://github.com/jonschlinkert/is-number/blob/master/test.js)

and just FYI, the code I pointed to above now has its own home and npm package: https://github.com/plotly/fast-isnumeric

**Comment by jonschlinkert** [comment]
> Isn't this whole isNumber just typeof value === "number" && isFinite(value); ?

no

**Comment by mattgrande** [comment]
I'm just wondering what the advantage of using `kind-of` is in this case (over using a standard `typeof`)?

**Comment by tunnckoCore** [comment]
Hm. Why not get just the number and string checks from `kind-of`?

Something like that?
```js
function isValid(val) {
  if (typeof val === 'string' || val instanceof String) {
    return val.length > 0; // we dont want empty strings
  }
  if (typeof val === 'number' || val instanceof Number) {
    return true;
  }
  return false;
}

module.exports = function isNumber(num) {
  if (!isValid(num)) {
    return false;
  }
  var n = +num;
  return (n - n + 1) >= 0;
};
```

It seems it works locally.

**Comment by jonschlinkert** [comment]
@tunnckoCore demonstrates this in a different way in his code:

```js
var five = new Number(5);
console.log(typeof five);
//=> object

console.log(five + 10);
//=> 15
```

Unlikely? Yes. But that's only one edge case. I like consistent, reliable, fast code. Given that this library's job is to check for numbers, I think it's reasonable to be more comprehensive the you might be in the average code project.

That said, my suggestion is that you try running your assumptions against the unit tests instead of asking here (since it's more likely to draw debate about things that are already answered in the code).

**Comment by tunnckoCore** [comment]
Tests are passing and benchmarks are still the fastest way.

![2016-09-01-18 15 10_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/18172917/2a1b20e0-7070-11e6-816c-6db8f07f19e1.png)

**Comment by jonschlinkert** [comment]
Ok, feel free to keep discussing. I'm always open to optimizations - so I'll check back from time to time to see if a conclusion is drawn that there is a definite optimization that is consistent and reliable. But I probably won't be active in the discussion.

**Comment by tunnckoCore** [comment]
Yea, no problems. I'll PR with just added new way to the `benchmark/code/` and we can see what to do, okey?

**Comment by dfcreative** [comment]
@jonschlinkert the painpoint is that such a good and natural name in npm is taken by such a shockingly large dependency, it breaks any thinkable expectations. I would not expect checking anything more than 'typeof' and 'instanceof', otherwise it is 'is-numeric' or else. That just undermines trust in npm.
Just an opinion.

**Comment by jonschlinkert** [comment]
"shockingly large" wtf are you talking about? 

locking.

**Comment by jonschlinkert** [comment]
@dfcreative your last comment was deleted as it was pejorative and antagonistic.
